### ISSUE TITLE
The code for Figure 3

### ISSUE THREAD

**Issue by MrZhengXin** [yanaiela/pararel#4]
Hi~ 
I'm wondering if the code of Figure 3, t-SNE could be added into the repository?

**Comment by yanaiela** [comment]
[Here it is](https://github.com/yanaiela/pararel/blob/main/notebooks/tsne-figures.ipynb)

Unfortunately I didn't use the random state variable in tsne for reproducing the exact same figure, but the one I got is close enough =)

Let me know if you have any troubles generating it.

**Comment by MrZhengXin** [comment]
> [Here it is](https://github.com/yanaiela/pararel/blob/main/notebooks/tsne-figures.ipynb)
> 
> Unfortunately I didn't use the random state variable in tsne for reproducing the exact same figure, but the one I got is close enough =)
> 
> Let me know if you have any troubles generating it.

Thank you very much indeed~
